### ISSUE TITLE
Can't use sponcycastle as jce provider in jre

### ISSUE THREAD

**Issue by pasqualm** [rtyley/spongycastle#31]
Hi 
I'm trying to use spongycastle as a jce prover for a jre in a desktop machine. I can't use bouncycastle for it because it creates a classloader conflict in another place of the machine. I added the core and prov jar's in $JRE/lib/ext and the line:
security.provider.9=org.spongycastle.jce.provider.BouncyCastleProvider

In $JRE/lib/security/java.security
Using this code:
http://www.java2s.com/Code/Java/Security/ListAllProviderAndItsAlgorithms.htm

I can check that spongycastle is correctly loaded but something must be wrong because, later I try to load some https url which must be served by spongycastle and it doesn't work. With an equivalent bouncycastle version it works.
The issue can be tested installing java 1.6, and using this code:
https://github.com/UniconLabs/java-keystore-ssl-test

In this way:
/usr/java/jdk1.6.0_45/bin/java -jar java-keystore-test-0.0.1.jar https://webpre.sedeb2b.com/EdiwinWS/services/geFactGva?wsdl

Before testing add to cacerts the root certificates in https://acedicom.edicomgroup.com/eu/caedicom_en.xml, please

This works when using bouncycastle as additional jce provider but not with spongycastle ¿any idea of what can be happening?

**Comment by willemw12** [comment]
The instructions to make Spongy Castle work are on the home page: https://rtyley.github.io/spongycastle.

For SSHJ this means it:

1) needs to also to accept provider name "SC"

2) should, for convenience, use "insertProviderAt(..., 1)" rather than "addProvider()"

The SSHJ files to change are: net/schmizz/sshj/common/SecurityUtils.java (and net/schmizz/sshj/userauth/keyprovider/PKCS8KeyFile.java).



Then as usual in your app/build.gradle file, define:

    dependencies {
        ...
        compile 'com.hierynomus:sshj:0.20.0'
        //compile 'com.madgag.spongycastle:core:1.54.0.0'
        compile 'com.madgag.spongycastle:pkix:1.54.0.0'
        //compile 'com.madgag.spongycastle:prov:1.54.0.0'
        compile 'org.slf4j:slf4j-android:1.7.22'
        ...
    }

And in your app code:

    SSHClient sshClient = new SSHClient(new AndroidConfig());
